version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - .env

volumes:
  postgres_data:
