apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  labels:
    app: fastapi
spec:
  type: LoadBalancer
  selector:
    app: fastapi  # <-- precisa bater com o label do seu deployment/pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
