apiVersion: v1
kind: Namespace
metadata:
  name: postgres-purchase-namespace
  labels:
    environment: production
    app: postgres
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  namespace: postgres-purchase-namespace
  labels:
    app: postgres
data:
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: postgres-purchase-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - database-purchase  # Nome do label do node
      containers:
        - name: postgres
          image: 'postgres:15'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-secret
          volumeMounts:
            - name: sql-files
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: sql-files
          configMap:
            name: database-sql
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: postgres-purchase-namespace
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-sql
  namespace: postgres-purchase-namespace
data:
  init-db1.sql: |
    
    create type public.TipoPagamentoEnum as enum (
      'CARTAO',
      'PIX',
      'BOLETO'
    );
    
    create table if not exists public.purchase(
      id_veiculo integer,
      id_comprador integer,
      tipo_pagamento public.TipoPagamentoEnum not null,
      dt_compra timestamp default current_timestamp,
      constraint pk_purchase primary key (id_veiculo)
    );
